In [20]:
from images import bigpycraft_bda as bpc
from IPython.display import Image 
from numpy.random import randn
import numpy as np

ImportError: cannot import name 'bigpycraft_bda' from 'images' (unknown location)

In [8]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = randn(8)

In [12]:
np.exp(arr)

array([17.37519763,  3.92406305,  0.29199583,  0.54433708,  0.2000681 ,
        0.74863294,  0.25331298,  2.82149346])

In [13]:
x = randn(8)
x

array([-0.2660811 ,  0.80141189,  0.21588664,  0.09975866, -0.5258492 ,
       -0.38292983, -0.12222433, -0.09151806])

In [14]:
y = randn(8)
y


array([-0.91320421,  0.06131739,  1.82572962, -0.79416764, -1.12450652,
        2.12924232, -2.1265775 ,  1.05621696])

In [15]:
np.maximum(x, y) # element-wise maximum


array([-0.2660811 ,  0.80141189,  1.82572962,  0.09975866, -0.5258492 ,
        2.12924232, -0.12222433,  1.05621696])

In [16]:
arr = randn(7) * 5
arr


array([10.50651342, -3.53077656, -3.87566989, -7.12087728, -4.5540874 ,
       -0.12984735,  0.79083249])

In [17]:
np.modf(arr)


(array([ 0.50651342, -0.53077656, -0.87566989, -0.12087728, -0.5540874 ,
        -0.12984735,  0.79083249]), array([10., -3., -3., -7., -4., -0.,  0.]))

In [18]:
Image(bpc.Table4_3)


NameError: name 'bpc' is not defined

In [19]:
Image(bpc.Table4_4)


NameError: name 'bpc' is not defined

In [ ]:
금융 데이터 

In [21]:
names = np.array(['Bob', 'Joe', 'Will','Bob', 'Will', 'Joe', 'joe'])
names 

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'joe'], dtype='<U4')

In [22]:
np.unique(names)

array(['Bob', 'Joe', 'Will', 'joe'], dtype='<U4')

In [23]:
ints = np.array([3,3,3,2,2,1,1,4,4])

In [24]:
np.unique(ints)

array([1, 2, 3, 4])

In [25]:
sorted(set(names))

['Bob', 'Joe', 'Will', 'joe']

In [26]:
values = np.array([6,0,0,3,2,5,6])
values

array([6, 0, 0, 3, 2, 5, 6])

In [27]:
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])

## Pandas

In [35]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [36]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [37]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [38]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [39]:
obj2 =Series([4,7,-5,3], index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [40]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [41]:
    obj2['a']

-5

In [43]:
obj2['d'] = 6

In [44]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [45]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [46]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [47]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

## 

In [48]:
'b' in obj2

True

In [50]:
'e' in obj2

False

In [52]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [53]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index = states)

In [54]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [55]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [56]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [57]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [59]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [60]:
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [61]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [63]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [64]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [65]:
obj.index = ['Bob', 'Steve','Jeff', 'Ryan']

In [67]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [69]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [70]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [71]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [73]:
obj2 = Series([4,7,-5,3], index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [74]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [75]:
obj2['a']

-5

In [77]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]


c    3
a   -5
d    6
dtype: int64

In [78]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [79]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [80]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [81]:
'b' in obj2

True

In [82]:
'e' in obj2

False

In [83]:
sdata = {'Ohio':35000, 'Texas': 71000, 'Oregon':16000, 'Utah':5000 }
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [84]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [86]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [87]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [88]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [89]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [90]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [92]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [93]:
obj4.name = 'popultarion'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: popultarion, dtype: float64

In [94]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [97]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [98]:
# DataFrame 객체 생성1
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year' : [2000, 2001, 2002, 2001, 2002],
        'pop'  : [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)


In [100]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [101]:
# 순서를 지정
DataFrame(data, columns=['year', 'state', 'pop'])


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [103]:
# DataFrame 객체 생성2
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [110]:
# DataFrame 객체 생성1
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year' : [2000, 2001, 2002, 2001, 2002],
        'pop'  : [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [109]:
frame

stata  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [111]:
# 순서를 지정
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [113]:
# DataFrame 객체 생성2
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [114]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [115]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [116]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [117]:
frame2.ix['three']

C:\python\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [119]:
frame2 [ 'debt'] = 16.5
frame2


year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [121]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [122]:
val = Series([-1.2,-1.5, -1.7], index = ['two', 'four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [128]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [129]:
# 칼럼을 삭제
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [130]:
frame2


year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [131]:
# DataFrame 객체 생성3  
# 중첩된 dict, 바깥 사전의 키값이 칼럼이 되고 안의 키는 로우가 된다.
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio'  : {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)

In [132]:
frame3


Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [134]:
# NumPy에서 처럼 결과값의 순서 뒤집기
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [135]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [136]:
obj['b']

1.0

In [137]:
obj[1]

1.0

In [138]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [139]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [140]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [141]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [142]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [143]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [146]:
data = DataFrame(np.arange(16).reshape((4,4)),
                 index = ['Ohio', 'Colorado', 'Utah',"New York"],
                 columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [147]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [148]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [149]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [150]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [151]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [152]:
data[data<5] = 0

In [153]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [157]:
data.ix[['Colorado', 'Utah'], [3,0,1]]

C:\python\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


four  one  two
Colorado     7    0    5
Utah        11    8    9

In [158]:
data.ix[2]

C:\python\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [159]:
data.ix[:'Utah', 'two']

C:\python\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [160]:
data.ix[data.three>5, :3]

C:\python\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [162]:
# DataFrame의 값 선택하기
Image(bpc.Table5_6, width=600)

NameError: name 'bpc' is not defined

In [163]:
s1 = Series([7.3,-2.5,3.4,1.5], index = ['a', 'c', 'd', 'e'])
s2 = Series([-2.1,3.6, -1.5,4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [164]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [165]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [166]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [168]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])



In [170]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [172]:
df1 = DataFrame(np.arange(12.).reshape((3,4)), columns= list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4,5)), columns= list('abcde'))

In [173]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [174]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [175]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [176]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [177]:
df1. reindex(columns = df2.columns, fill_value =0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [178]:
arr= np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [179]:
arr[0]

array([0., 1., 2., 3.])

In [180]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [182]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [186]:
series = frame.iloc[0]
series 

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [188]:
frame - series


b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [192]:
series2 = Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [194]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [195]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

## 

In [197]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [198]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [199]:
frame.sub(series3, axis=0)


b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [200]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [202]:
frame

b         d         e
Utah    0.903509 -0.799695  1.149543
Ohio   -1.459538 -0.379107 -0.345073
Texas   0.162362 -0.219883  0.562174
Oregon -0.963607  0.978898 -1.570839

In [203]:
np.abs(frame)


b         d         e
Utah    0.903509  0.799695  1.149543
Ohio    1.459538  0.379107  0.345073
Texas   0.162362  0.219883  0.562174
Oregon  0.963607  0.978898  1.570839

In [204]:
f = lambda x: x.max() - x.min()

In [205]:
frame.apply(f)

b    2.363047
d    1.778592
e    2.720382
dtype: float64

In [ ]:
arr = np

In [ ]:
frame = DataFrame(np)

In [207]:
frame = DataFrame(np.random.randn(4,3),columns = list('bde'),
                 index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [208]:
frame

b         d         e
Utah    0.231980  0.021320  1.397328
Ohio   -0.840362  1.638834 -0.877243
Texas   0.474079  1.846352 -0.384515
Oregon -0.196166  0.217570 -2.538809

In [209]:
np.abs(frame)

b         d         e
Utah    0.231980  0.021320  1.397328
Ohio    0.840362  1.638834  0.877243
Texas   0.474079  1.846352  0.384515
Oregon  0.196166  0.217570  2.538809

In [210]:
f = lambda x: x.max() -x.min()

In [211]:
frame.apply(f)

b    1.314442
d    1.825033
e    3.936138
dtype: float64

In [214]:
frame.apply(f,axis = 1)

Utah      1.376008
Ohio      2.516077
Texas     2.230867
Oregon    2.756380
dtype: float64

In [218]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

b         d         e
min -0.840362  0.021320 -2.538809
max  0.474079  1.846352  1.397328

In [220]:
frame

b         d         e
Utah    0.231980  0.021320  1.397328
Ohio   -0.840362  1.638834 -0.877243
Texas   0.474079  1.846352 -0.384515
Oregon -0.196166  0.217570 -2.538809

In [222]:
format = lambda x: '%.2f'% x
frame.applymap(format)

b     d      e
Utah     0.23  0.02   1.40
Ohio    -0.84  1.64  -0.88
Texas    0.47  1.85  -0.38
Oregon  -0.20  0.22  -2.54

In [224]:
frame['e'].map(format)

Utah       1.40
Ohio      -0.88
Texas     -0.38
Oregon    -2.54
Name: e, dtype: object

In [225]:
obj = Series(range(4), index = ['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [226]:
frame = DataFrame(np.arange(8).reshape((2,4)), index =['three','one'],
                 columns = ['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [227]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [228]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [230]:
obj = Series([4, 7, -3, 2])
# obj.order()
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [231]:
obj = Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [232]:
frame = DataFrame({'b':[4,7,-3,2], 'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [233]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [234]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [235]:
obj = Series([7,-5,4,2,0,4])
obj

0    7
1   -5
2    4
3    2
4    0
5    4
dtype: int64

In [236]:
obj.rank()

0    6.0
1    1.0
2    4.5
3    3.0
4    2.0
5    4.5
dtype: float64

In [237]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    4.0
3    3.0
4    2.0
5    5.0
dtype: float64

In [239]:
obj.rank(ascending=False, method ='max')

0    1.0
1    6.0
2    3.0
3    4.0
4    5.0
5    3.0
dtype: float64

In [241]:
obj.rank(ascending=False, method = 'dense')

0    1.0
1    5.0
2    2.0
3    3.0
4    4.0
5    2.0
dtype: float64

In [242]:
frame = DataFrame({'b':[4.3, 7, -3, 2],
                  'a':[0,1,0,1],
                  'c': [-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [243]:
frame.rank(axis = 1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [244]:
obj = Series(range(5), index = ['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [246]:
obj.index.is_unique

False

In [247]:
obj['a']


a    0
a    1
dtype: int64

In [248]:
obj['c']

4

In [249]:
df = DataFrame(np.random.randn(4,3), index = ['a', 'a', 'b', 'b'])
df

0         1         2
a  0.482217  0.761426 -0.842715
a -2.471868 -0.598764 -0.302176
b  0.352480 -2.748609 -0.718221
b  0.186164  0.242959 -0.876894

In [250]:
df.loc['b']

0         1         2
b  0.352480 -2.748609 -0.718221
b  0.186164  0.242959 -0.876894

In [252]:
import re

In [254]:
result = re.findall('a', text)
result

NameError: name 'text' is not defined

In [256]:
import re

In [257]:
text = 'Myid number is [G203_5A]'
text

'Myid number is [G203_5A]'

In [258]:
result = re.findall('a',text)

In [260]:
result

[]

In [262]:
result = re.findall('A', text)
result

['A']

In [264]:
result = re.findall('i',text)
result

['i', 'i']

In [265]:
result = re.findall('[a-z]', text)
result

['y', 'i', 'd', 'n', 'u', 'm', 'b', 'e', 'r', 'i', 's']

In [267]:
result = re.findall('[a-z]+', text)
result

['yid', 'number', 'is']

In [268]:
result = re.findall('[A-Z]', text)
result

['M', 'G', 'A']

In [269]:
result = re.findall('[0-9]+', text)

In [272]:
result = re.findall('[0-9]+', text)
result

['203', '5']

In [273]:
result = re.findall('[a-zA-Z0-9]', text)
result 

['M',
 'y',
 'i',
 'd',
 'n',
 'u',
 'm',
 'b',
 'e',
 'r',
 'i',
 's',
 'G',
 '2',
 '0',
 '3',
 '5',
 'A']

In [274]:
result = re.findall('[\w]+', text)
result 

['Myid', 'number', 'is', 'G203_5A']

In [276]:
result = re.findall('[\w]', text)
result

['M',
 'y',
 'i',
 'd',
 'n',
 'u',
 'm',
 'b',
 'e',
 'r',
 'i',
 's',
 'G',
 '2',
 '0',
 '3',
 '_',
 '5',
 'A']

In [277]:
text = """
옛날 옛적에 김진수라는 사람이 살았습니다.
그에게는 5형제가 있었는데, 김진수, 김진구, 김진용, 김진태, 김진욱 이렇게 5명 있었습니다.
그리고 그는 결혼을 해서 김찬영, 김준영, 김채영 3남매를 낳고 행복하게 잘 살았습니다.
"""
# 형제 : 김진O
# 자녀 : 김O영

In [278]:
pattern = re.compile('김진\w')


In [279]:
brother = pattern.findall(text)
brother

['김진수', '김진수', '김진구', '김진용', '김진태', '김진욱']

In [280]:
pattern = re.compile('김.영')
pattern = re.compile('김\w영')

In [283]:
children = pattern.findall(text)
children

['김찬영', '김준영', '김채영']

In [285]:
brother = set(brother)
brother

{'김진구', '김진수', '김진용', '김진욱', '김진태'}

In [288]:
text = "A sky, a dragonfly and a butterfly!!!!!"

In [289]:
pattern = re.compile("\w+fly")
pattern.findall(text)

['dragonfly', 'butterfly']

In [291]:
text = """
    010-5670-3847   # space, -, . => []
    010 5670 3847
    010.5670 3847
"""

In [292]:
pattern = re.compile('=d{3}[ -.]?\d{4}[ -.]?\d{4}')

In [294]:
pattern.findall(text)

[]

In [296]:
text = """
    010-5670-3847   # space, -, . => []
    옛날에는 011-1052-3847 이랬는데..
    010 5670 3847
    010.-5670 3847
    사는동네가 자이아파트 516동512호
    그리구, 사무실번호는 02-360-4047이고
    우편번호는 100-791, 청파로 463번지
    
"""

In [298]:
pattern = re.compile("\d{3}[ -\.]{1,2}\d{3,4}[ -\.]?\d{4}")


In [300]:
pattern.findall(text)

['010-5670-3847', '011-1052-3847', '010 5670 3847', '010.-5670 3847']

In [301]:
pattern = re.compile('\d{2,3}[ -\.]?\d{3,4}[ -\.]?\d{4}')

In [303]:
pattern.findall(text)

['010-5670-3847', '011-1052-3847', '010 5670 3847', '02-360-4047']

In [305]:
text = """
옛날 옛적에 김진수라는 사람이 살았습니다.
그에게는 5형제가 있었는데, 김진수, 김진구, 김진용, 김진태, 김진욱 이렇게 5명 있었습니다.
그리고 그는 결혼을 해서 김찬영, 김준영, 김채영 3남매를 낳고 행복하게 잘 살았습니다.
"""
# 형제 : 김진O
# 자녀 : 김O영


In [307]:
# import re 를 통해 모듈을 임포트한 뒤, p = re.compile('정규표현식')을 통해서 
#정규표현식을 컴파일하고, 컴파일된 패턴 객체(p)를 이용하여 
#이 객체가 가지고 있는 메서드를 통해 작업을 수행할 수 있다.

In [309]:
text = """
    김찬영 020822-3069110
    김준영 040825-3069115
    김채영 110715-4063111
"""

In [310]:
pattern = re.compile("\d{6}-?\d{7}")



In [311]:
pattern.findall(text)

['020822-3069110', '040825-3069115', '110715-4063111']

In [319]:
pattern = re.compile("\d{6}-\d{7}")
# 정규표현식 GROUP
# 1. 생년월일 그룹 <birth>
# 2. 주민등록번호 뒷자리 그룹 <secret>

In [320]:
pattern = re.compile("(?P<birth>\d{6})-(?P<secret>\d{7})")

# 김채영 110715-******* => 김채영(110715-*******)

In [321]:
pattern.findall(text)

[('020822', '3069110'), ('040825', '3069115'), ('110715', '4063111')]

In [323]:
result =pattern.sub('\g<birth>-*******', text)
print(result)


    김찬영 020822-*******
    김준영 040825-*******
    김채영 110715-*******



In [325]:
pattern.findall(text)

[('020822', '3069110'), ('040825', '3069115'), ('110715', '4063111')]

In [327]:
print(text)


    김찬영 020822-3069110
    김준영 040825-3069115
    김채영 110715-4063111



In [332]:
pattern = re.compile("(?P<name>\w{3}) (?P<birth>\d{6})-(?P<secret>\d{7})")


In [334]:
pattern.findall(text)


[('김찬영', '020822', '3069110'),
 ('김준영', '040825', '3069115'),
 ('김채영', '110715', '4063111')]

In [336]:
result = pattern.sub('\g<name>(\g<birth>-******)', text)
print(result)


    김찬영(020822-******)
    김준영(040825-******)
    김채영(110715-******)



In [346]:
result = pattern.sub("\g<name>(\g<birth>-*******)", text)
print(result)


    김찬영(020822-*******)
    김준영(040825-*******)
    김채영(110715-*******)



In [347]:
result = result.split('\n')
result

['',
 '    김찬영(020822-*******)',
 '    김준영(040825-*******)',
 '    김채영(110715-*******)',
 '']

In [348]:
result.pop(0)
result

['    김찬영(020822-*******)',
 '    김준영(040825-*******)',
 '    김채영(110715-*******)',
 '']

In [351]:
result.pop(-1)
result

['    김찬영(020822-*******)']

In [353]:
for idx,val in enumerate(result):
    val = val.replace(' ', '')
    print(idx, val)

0 김찬영(020822-*******)


In [355]:
pattern = re.compile("\d{?}+?\d{?}+?\d{?}")
pattern

re.compile(r'\d{?}+?\d{?}+?\d{?}', re.UNICODE)

In [ ]:
text = "A sky, a dragonfly and a butterfly!!!!!"

In [356]:
pattern  = re.compile('\w+fly')
pattern.findall(text)

[]

In [357]:
text = """
    010-5670-3847   # space, -, . => []
    010 5670 3847
    010.5670 3847
"""

In [359]:
pattern = re.compile('\d{3}[ -.]?\d{4}[ -.]?\d{4}')
pattern.findall(text)

['010-5670-3847', '010 5670 3847', '010.5670 3847']

In [360]:
%ls data

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2C50-3BD8

 C:\Users\202-001\실습\data 디렉터리

2019-08-22  오전 09:50    <DIR>          .
2019-08-22  오전 09:50    <DIR>          ..
2019-08-20  오후 03:37    <DIR>          .ipynb_checkpoints
2019-08-20  오후 04:07               310 company.csv
2019-08-20  오후 03:37                23 hello.txt
2019-08-20  오후 04:05               148 students.csv
2019-08-20  오후 03:45                30 subject.txt
               4개 파일                 511 바이트
               3개 디렉터리  81,160,937,472 바이트 남음


In [361]:
text = []

In [362]:
text = "A sky, a dragonfly and a butterfly!!!!!"

In [364]:
pattern = re.compile("\w+fly")
pattern.findall(text)

['dragonfly', 'butterfly']

In [365]:
pattern = re.compile("\w+fly")
pattern.findall(text)

['dragonfly', 'butterfly']

In [368]:
pattern = re.compile("\d{3}[ -.]?\d{4}[ -.]?\d{4}")


In [370]:
pattern.findall(text)


[]

In [372]:
text = """
    010-5670-3847   # space, -, . => []
    옛날에는 011-1052-3847 이랬는데..
    010 5670 3847
    010.-5670 3847
    사는동네가 자이아파트 516동512호
    그리구, 사무실번호는 02-360-4047이고
    우편번호는 100-791, 청파로 463번지
    
"""

In [375]:
pattern = re.compile("\d{3}[ -\.]{1,2}\d{3,4}[ -\.]?\d{4}")


In [377]:
pattern.findall(text)


['010-5670-3847', '011-1052-3847', '010 5670 3847', '010.-5670 3847']

In [378]:
text = """
    김찬영 020822-3069110
    김준영 040825-3069115
    김채영 110715-4063111
"""

In [ ]:
pattern = re.compile

In [ ]:
#re.compile() : 

In [390]:
from IPython.display import Image

from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [391]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [382]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [384]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [392]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [393]:
df.mean(axis=1, skipna=True)


a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [396]:
reference(Table5_9, 450)


NameError: name 'reference' is not defined

In [399]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [400]:
df.idxmax()

one    b
two    d
dtype: object

In [402]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [404]:
df.describe()


one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [405]:
obj = Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [406]:
obj = Series(['c','a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [408]:
uniques = obj.unique()
uniques

array(['c'], dtype=object)

In [409]:
obj.value_counts()

c    1
dtype: int64

In [410]:
pd.value_counts(obj.values, sort = False)

c    1
dtype: int64

In [412]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [415]:
import pandas as pd
data = [1,3,5,7,9]
s = pd.Series(data)
s


0    1
1    3
2    5
3    7
4    9
dtype: int64

In [418]:
data = {
    'year': [2016, 2017, 2018],
    'GDP rate': [2.8, 3.1, 3.0],
    'GDP': ['1.637M', '1.73M', '1.83M']
}
 
df = pd.DataFrame(data)
df

year  GDP rate     GDP
0  2016       2.8  1.637M
1  2017       3.1   1.73M
2  2018       3.0   1.83M

In [419]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [422]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [424]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
               index = ['a', 'b', 'c', 'd'], 
               columns = ['one', 'two'])
df


one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [425]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [427]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [429]:
df.mean(axis = 1, skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [431]:
df.mean(axis =1, skipna = True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [432]:
df.mean(axis = 1, skipna = True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [434]:
reference(Table5_9,450)

NameError: name 'reference' is not defined

In [436]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [437]:
# 최대/최소값을 가지고 있는 index를 반환
df.idxmax()

one    b
two    d
dtype: object

In [438]:
# cumulative sum
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [439]:
# decribe() : 메소드는 생성했던 DataFrame의 간단한 통계 정보를 보여줌
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [441]:
obj = Series(['a','a','b','c']*4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [442]:
['a','a','b','c']*4

['a',
 'a',
 'b',
 'c',
 'a',
 'a',
 'b',
 'c',
 'a',
 'a',
 'b',
 'c',
 'a',
 'a',
 'b',
 'c']

In [444]:
reference(Table5_10, 600)


NameError: name 'reference' is not defined

In [447]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])


In [449]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [450]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [451]:
pd.value_counts(obj.values, sort = False)

b    2
d    1
c    3
a    3
dtype: int64

In [452]:
pd.value_counts(obj.values, sort = True)

a    3
c    3
b    2
d    1
dtype: int64

In [454]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [455]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [456]:
# 순서를 나타내는 정수 기반의 2차원 인덱싱
pd.iloc()

AttributeError: module 'pandas' has no attribute 'iloc'

In [457]:
data = DataFrame({'Qu1': [1, 3, 4, 3, 4],
                  'Qu2': [2, 3, 1, 2, 3],
                  'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [459]:
# fillna(0) : 결측값을 0으로 채운다
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [461]:
from IPython.display import Image

from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [462]:
# np.nan : 정의할 수 없는 숫자를 나타낸다(numpy not a number)
string_data = Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [464]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [468]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [470]:
reference(Table5_12, 600)


NameError: name 'reference' is not defined

In [473]:
from numpy import nan as NA
data = Series([1,NA,3.5, NA, 7])


In [474]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [476]:
data= DataFrame([[1.,6.5,3.], [1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [479]:
cleaned = data.dropna()
cleaned


0    1    2
0  1.0  6.5  3.0

In [481]:
# 모든 값이 NA인 로우만 제외

data.dropna(how = 'all')


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [483]:
data[4] = NA
data


0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [485]:
data.dropna(axis = 1, how= 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [487]:
# numpy.random.randn(n, m)을 이용하여 표준 정규 분포에서 무작위 배열을 생성
df = DataFrame(np.random.randn(7,3))
df

0         1         2
0 -0.922333 -0.551994  0.699494
1 -1.461657 -0.824427  1.192796
2  0.885564  0.512028 -1.227205
3 -1.095817 -0.030105 -1.062066
4  1.383177  1.243087  0.117995
5 -1.388422  0.648000  1.248404
6 -0.809775  1.498538 -0.106231

In [489]:
# iloc  : # 순서를 나타내는 정수 기반의 2차원 인덱싱
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0 -0.922333       NaN       NaN
1 -1.461657       NaN       NaN
2  0.885564       NaN -1.227205
3 -1.095817       NaN -1.062066
4  1.383177  1.243087  0.117995
5 -1.388422  0.648000  1.248404
6 -0.809775  1.498538 -0.106231

In [491]:
df.dropna(thresh = 3)


0         1         2
4  1.383177  1.243087  0.117995
5 -1.388422  0.648000  1.248404
6 -0.809775  1.498538 -0.106231

In [493]:
df.dropna(thresh = 2)

0         1         2
2  0.885564       NaN -1.227205
3 -1.095817       NaN -1.062066
4  1.383177  1.243087  0.117995
5 -1.388422  0.648000  1.248404
6 -0.809775  1.498538 -0.106231

In [495]:
df

0         1         2
0 -0.922333       NaN       NaN
1 -1.461657       NaN       NaN
2  0.885564       NaN -1.227205
3 -1.095817       NaN -1.062066
4  1.383177  1.243087  0.117995
5 -1.388422  0.648000  1.248404
6 -0.809775  1.498538 -0.106231

In [497]:
df.fillna(0)

0         1         2
0 -0.922333  0.000000  0.000000
1 -1.461657  0.000000  0.000000
2  0.885564  0.000000 -1.227205
3 -1.095817  0.000000 -1.062066
4  1.383177  1.243087  0.117995
5 -1.388422  0.648000  1.248404
6 -0.809775  1.498538 -0.106231

In [499]:
df.fillna({1:0.5, 3:-1})
##/

0         1         2
0 -0.922333  0.500000       NaN
1 -1.461657  0.500000       NaN
2  0.885564  0.500000 -1.227205
3 -1.095817  0.500000 -1.062066
4  1.383177  1.243087  0.117995
5 -1.388422  0.648000  1.248404
6 -0.809775  1.498538 -0.106231

In [501]:
##??????????

# fillna는 값을 채워 넣은 객체의 참조를 반환한다.

_= df.fillna(0, inplace = True)
df

0         1         2
0 -0.922333  0.000000  0.000000
1 -1.461657  0.000000  0.000000
2  0.885564  0.000000 -1.227205
3 -1.095817  0.000000 -1.062066
4  1.383177  1.243087  0.117995
5 -1.388422  0.648000  1.248404
6 -0.809775  1.498538 -0.106231

In [503]:
df = DataFrame(np.random.randn(6,3))
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA
df


0         1         2
0 -0.804911  1.759184 -0.390695
1  0.611690 -0.016137  1.347069
2  1.547025       NaN -1.088313
3 -0.999697       NaN  0.503474
4  0.484835       NaN       NaN
5 -0.576681       NaN       NaN

In [505]:
# method = 'ffill' :
df.fillna(method = 'ffill')

0         1         2
0 -0.804911  1.759184 -0.390695
1  0.611690 -0.016137  1.347069
2  1.547025 -0.016137 -1.088313
3 -0.999697 -0.016137  0.503474
4  0.484835 -0.016137  0.503474
5 -0.576681 -0.016137  0.503474

In [507]:
df.fillna(method = 'ffill', limit = 2)


0         1         2
0 -0.804911  1.759184 -0.390695
1  0.611690 -0.016137  1.347069
2  1.547025 -0.016137 -1.088313
3 -0.999697 -0.016137  0.503474
4  0.484835       NaN  0.503474
5 -0.576681       NaN  0.503474

In [509]:
data = Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [511]:
df = pd.DataFrame(np.random.randn(10,4))

In [513]:
df


0         1         2         3
0 -0.411434  1.200118  1.276113 -0.686343
1 -1.063913  0.044191 -0.179998 -0.702605
2  1.326849 -0.074282 -0.894627 -0.272965
3 -1.373114  2.079218  0.050458 -0.322018
4 -1.022366  0.649872 -1.551221  0.256588
5  0.062570  0.794112  0.613982 -1.376737
6 -0.549553 -0.213696  0.152504  0.725114
7 -0.743703 -1.995500 -0.394075 -0.084045
8  0.749436 -0.775781  0.395128  0.054778
9  0.401427  0.156374  0.190059  0.480916

In [ ]:
# concat : 데이터의 속성 형태가 동일한 데이터셋(homogeneously-typed objects)끼리 
#합칠 때 사용할 수 있는 pandas의 DataFrame 합치는 방법



In [ ]:
# Join  : sql 스타일로 합침. 

In [519]:
left = pd.DataFrame({'Lkey': ['foo', 'foo'], 'lval': [1, 2]})
right = pd.DataFrame({'Rkey': ['foo', 'foo'], 'rval': [4, 5]})



In [520]:
left

Lkey  lval
0  foo     1
1  foo     2

In [521]:
right

Rkey  rval
0  foo     4
1  foo     5

In [522]:
pd.merge(left, right, on='key')

KeyError: 'key'

## Matplot

In [ ]:
%matplotlib%matplotlib inline
 inline
